const wordContainer = document.querySelector('.word');
const words = [
    { word: "galaxy", definition: "A system of millions or billions of stars, together with gas and dust, held together by gravitational attraction." },
    { word: "horizon", definition: "The line where the earth's surface and the sky appear to meet." },
    { word: "oasis", definition: "A fertile spot in a desert, where water is found." },
    { word: "velocity", definition: "The speed of something in a given direction." },
    { word: "pinnacle", definition: "The most successful point; the culmination." },
    { word: "serendipity", definition: "The occurrence of events by chance in a happy or beneficial way." },
    { word: "quarantine", definition: "A period of isolation imposed to prevent the spread of disease." },
    { word: "labyrinth", definition: "A complicated irregular network of passages or paths in which it is difficult to find one's way; a maze." },
    { word: "ephemeral", definition: "Lasting for a very short time." },
    { word: "utopia", definition: "An imagined place or state of things in which everything is perfect." },
    { word: "zenith", definition: "The highest point reached by a celestial or other object." },
    { word: "nostalgia", definition: "A sentimental longing or wistful affection for the past." },
    { word: "silhouette", definition: "The dark shape and outline of someone or something visible against a lighter background." },
    { word: "paradigm", definition: "A typical example or pattern of something; a model." },
    { word: "cascade", definition: "A small waterfall, typically one of several that fall in stages down a steep rocky slope." },
    { word: "eclipse", definition: "The partial or total blocking of one celestial body by another." },
    { word: "ambience", definition: "The character and atmosphere of a place." },
    { word: "inception", definition: "The establishment or starting point of an institution or activity." },
    { word: "harmony", definition: "The combination of simultaneously sounded musical notes to produce a pleasing effect." },
    { word: "melancholy", definition: "A feeling of pensive sadness, typically with no obvious cause." },
    { word: "oblivion", definition: "The state of being unaware or unconscious of what is happening around you." },
    { word: "solace", definition: "Comfort or consolation in a time of distress or sadness." },
    { word: "vortex", definition: "A whirling mass of fluid or air, especially a whirlpool or whirlwind." },
    { word: "zephyr", definition: "A soft, gentle breeze." },
    { word: "ascend", definition: "To go up or climb." },
    { word: "verdant", definition: "Green with grass or other rich vegetation." },
    { word: "resilient", definition: "Able to withstand or recover quickly from difficult conditions." },
    { word: "ethereal", definition: "Extremely delicate and light in a way that seems not of this world." },
    { word: "luminary", definition: "A person who inspires or influences others, especially one prominent in a particular sphere." },
    { word: "facet", definition: "One side of something many-sided, especially of a cut gem." },
    { word: "tranquil", definition: "Free from disturbance; calm." },
    { word: "forlorn", definition: "Pitifully sad and abandoned or lonely." },
    { word: "eloquent", definition: "Fluent or persuasive in speaking or writing." },
    { word: "halcyon", definition: "Denoting a period of time in the past that was idyllically happy and peaceful." },
    { word: "reverie", definition: "A state of being pleasantly lost in one's thoughts; a daydream." },
    { word: "opaque", definition: "Not able to be seen through; not transparent." },
    { word: "serene", definition: "Calm, peaceful, and untroubled; tranquil." },
    { word: "oblivion", definition: "The state of being unaware or unconscious of what is happening around you." },
    { word: "solace", definition: "Comfort or consolation in a time of distress or sadness." },
    { word: "vortex", definition: "A whirling mass of fluid or air, especially a whirlpool or whirlwind." },
    { word: "zephyr", definition: "A soft, gentle breeze." },
    { word: "ascend", definition: "To go up or climb." },
    { word: "verdant", definition: "Green with grass or other rich vegetation." },
    { word: "resilient", definition: "Able to withstand or recover quickly from difficult conditions." },
    { word: "ethereal", definition: "Extremely delicate and light in a way that seems not of this world." },
    { word: "luminary", definition: "A person who inspires or influences others, especially one prominent in a particular sphere." },
    { word: "facet", definition: "One side of something many-sided, especially of a cut gem." },
    { word: "tranquil", definition: "Free from disturbance; calm." },
    { word: "forlorn", definition: "Pitifully sad and abandoned or lonely." },
    { word: "eloquent", definition: "Fluent or persuasive in speaking or writing." },
    { word: "halcyon", definition: "Denoting a period of time in the past that was idyllically happy and peaceful." },
    { word: "reverie", definition: "A state of being pleasantly lost in one's thoughts; a daydream." },
    { word: "opaque", definition: "Not able to be seen through; not transparent." },
    { word: "serene", definition: "Calm, peaceful, and untroubled; tranquil." },
    { word: "solitude", definition: "The state or situation of being alone." },
    { word: "exuberant", definition: "Filled with or characterized by a lively energy and excitement." },
    { word: "mirth", definition: "Amusement, especially as expressed in laughter." },
    { word: "ardent", definition: "Very enthusiastic or passionate." },
    { word: "luminous", definition: "Full of or shedding light; bright or shining, especially in the dark." },
    { word: "epiphany", definition: "A moment of sudden revelation or insight." },
    { word: "catharsis", definition: "The process of releasing, and thereby providing relief from, strong or repressed emotions." },
    { word: "vestige", definition: "A trace of something that is disappearing or no longer exists." },
    { word: "sublime", definition: "Of such excellence, grandeur, or beauty as to inspire great admiration or awe." },
    { word: "profound", definition: "Very great or intense; having or showing great knowledge or insight." },
    { word: "reminiscent", definition: "Tending to remind one of something." },
    { word: "amalgamate", definition: "Combine or unite to form one organization or structure." },
    { word: "inundate", definition: "Overwhelm (someone) with things or people to be dealt with; flood." },
    { word: "perplex", definition: "Make (someone) feel completely baffled." },
    { word: "tenacious", definition: "Tending to keep a firm hold of something; clinging or adhering closely." },
    { word: "nuance", definition: "A subtle difference in or shade of meaning, expression, or sound." },
    { word: "euphoria", definition: "A feeling or state of intense excitement and happiness." },
    { word: "tranquility", definition: "The quality or state of being tranquil; calm." },
    { word: "lucid", definition: "Expressed clearly; easy to understand." },
    { word: "intrepid", definition: "Fearless; adventurous." },
    { word: "eloquence", definition: "Fluent or persuasive speaking or writing." },
    { word: "bliss", definition: "Perfect happiness; great joy." },
    { word: "zealous", definition: "Having or showing great energy or enthusiasm in pursuit of a cause or objective." },
    { word: "idyllic", definition: "Extremely happy, peaceful, or picturesque." },
    { word: "hindsight", definition: "Understanding of a situation or event only after it has happened or developed." },
    { word: "opulent", definition: "Ostentatiously rich and luxurious or lavish." },
    { word: "enigmatic", definition: "Difficult to interpret or understand; mysterious." },
    { word: "sagacious", definition: "Having or showing keen mental discernment and good judgment; wise or shrewd." },
    { word: "ineffable", definition: "Too great or extreme to be expressed or described in words." },
    { word: "labyrinthine", definition: "Like a labyrinth; irregular and twisting." },
    { word: "jubilant", definition: "Feeling or expressing great happiness and triumph." },
    { word: "vivacious", definition: "Attractively lively and animated." },
    { word: "bewilder", definition: "Cause (someone) to become perplexed and confused." },
    { word: "gregarious", definition: "Fond of company; sociable." },
    { word: "quintessential", definition: "Representing the most perfect or typical example of a quality or class." },
    { word: "resplendent", definition: "Attractive and impressive through being richly colorful or sumptuous." },
    { word: "audacious", definition: "Showing a willingness to take surprisingly bold risks." },
    { word: "effervescent", definition: "Vivacious and enthusiastic." },
    { word: "pristine", definition: "In its original condition; unspoiled." },
    { word: "ephemeral", definition: "Lasting for a very short time." },
    { word: "perseverance", definition: "Persistence in doing something despite difficulty or delay in achieving success." },
    { word: "meticulous", definition: "Showing great attention to detail; very careful and precise." },
    { word: "epiphany", definition: "A moment of sudden revelation or insight." },
    { word: "ambiguous", definition: "Open to more than one interpretation; not having one obvious meaning." },
    { word: "benevolent", definition: "Well-meaning and kindly." },
    { word: "gregarious", definition: "Fond of company; sociable." },
    { word: "clairvoyant", definition: "A person who claims to have a supernatural ability to perceive events in the future or beyond normal sensory contact." },
    { word: "inevitable", definition: "Certain to happen; unavoidable." },
    { word: "nostalgia", definition: "A sentimental longing or wistful affection for the past." },
    { word: "serendipity", definition: "The occurrence of events by chance in a happy or beneficial way." },
    { word: "tranquility", definition: "The quality or state of being tranquil; calm." },
    { word: "lucid", definition: "Expressed clearly; easy to understand." },
    { word: "intrepid", definition: "Fearless; adventurous." },
    { word: "eloquence", definition: "Fluent or persuasive speaking or writing." },
    { word: "bliss", definition: "Perfect happiness; great joy." },
    { word: "zealous", definition: "Having or showing great energy or enthusiasm in pursuit of a cause or objective." },
    { word: "idyllic", definition: "Extremely happy, peaceful, or picturesque." },
    { word: "enigmatic", definition: "Difficult to interpret or understand; mysterious." },
    { word: "sagacious", definition: "Having or showing keen mental discernment and good judgment; wise or shrewd." },
    { word: "ineffable", definition: "Too great or extreme to be expressed or described in words." },
    { word: "labyrinthine", definition: "Like a labyrinth; irregular and twisting." },
    { word: "jubilant", definition: "Feeling or expressing great happiness and triumph." },
    { word: "vivacious", definition: "Attractively lively and animated." },
    { word: "bewilder", definition: "Cause (someone) to become perplexed and confused." },
    { word: "gregarious", definition: "Fond of company; sociable." },
    { word: "quintessential", definition: "Representing the most perfect or typical example of a quality or class." },
    { word: "resplendent", definition: "Attractive and impressive through being richly colorful or sumptuous." },
    { word: "audacious", definition: "Showing a willingness to take surprisingly bold risks." },
    { word: "effervescent", definition: "Vivacious and enthusiastic." },
    { word: "pristine", definition: "In its original condition; unspoiled." },
    { word: "whimsical", definition: "Playfully quaint or fanciful, especially in an appealing and amusing way." },
    { word: "reverence", definition: "Deep respect for someone or something." },
    { word: "solitude", definition: "The state or situation of being alone." },
    { word: "luminous", definition: "Full of or shedding light; bright or shining, especially in the dark." },
    { word: "vestige", definition: "A trace of something that is disappearing or no longer exists." },
    { word: "sublime", definition: "Of such excellence, grandeur, or beauty as to inspire great admiration or awe." },
    { word: "profound", definition: "Very great or intense; having or showing great knowledge or insight." },
    { word: "serene", definition: "Calm, peaceful, and untroubled; tranquil." },
    { word: "exquisite", definition: "Extremely beautiful and delicate." },
    { word: "majestic", definition: "Having or showing impressive beauty or dignity." },
    { word: "radiant", definition: "Sending out light; shining or glowing brightly." },
    { word: "melodious", definition: "Having a pleasant tune; tuneful." },
    { word: "empathy", definition: "The ability to understand and share the feelings of another." },
    { word: "eclectic", definition: "Deriving ideas, style, or taste from a broad and diverse range of sources." },
    { word: "rejuvenate", definition: "Make (someone or something) look or feel younger, fresher, or more lively." }, { word: "ark", definition: "A boat or ship; often refers to Noah's Ark." },
    { word: "bee", definition: "An insect known for its role in pollination and honey production." },
    { word: "cat", definition: "A small domesticated carnivorous mammal." },
    { word: "dawn", definition: "The first appearance of light in the sky before sunrise." },
    { word: "echo", definition: "A sound or sounds caused by the reflection of sound waves from a surface." },
    { word: "fern", definition: "A flowerless plant with feathery or leafy fronds." },
    { word: "glee", definition: "Great delight or happiness." },
    { word: "harm", definition: "Physical injury or damage to someone's health or property." },
    { word: "icon", definition: "A symbol or graphic representation." },
    { word: "jade", definition: "A hard green gemstone." },
    { word: "keen", definition: "Having or showing eagerness or enthusiasm." },
    { word: "lamb", definition: "A young sheep." },
    { word: "maze", definition: "A complex network of paths or passages." },
    { word: "nest", definition: "A structure made by birds or insects to lay eggs and rear their young." },
    { word: "omen", definition: "An event regarded as a sign of good or evil." },
    { word: "peel", definition: "To remove the outer covering or skin from a fruit or vegetable." },
    { word: "quill", definition: "A pen made from a bird's feather, or a spine of a porcupine." },
    { word: "rose", definition: "A type of fragrant flower known for its beauty." },
    { word: "star", definition: "A massive, luminous celestial body in space." },
    { word: "tide", definition: "The periodic rise and fall of the sea level." },
    { word: "undo", definition: "To reverse an action or remove an effect." },
    { word: "vase", definition: "A container used to hold flowers or as decoration." },
    { word: "wolf", definition: "A wild carnivorous mammal related to the domestic dog." },
    { word: "yarn", definition: "A long, continuous strand of fibers used in knitting or weaving." },
    { word: "zest", definition: "Great enthusiasm and energy, or the outer peel of citrus fruits." }

]; 
let randomNum = Math.floor(Math.random() * words.length);
const word = words[randomNum].word; 
const descrip = document.getElementById("definition");
descrip.innerText = words[randomNum].definition;

function renderWord(word) {
    wordContainer.innerHTML = ''; 
    word.split('').forEach(() => {
        const li = document.createElement('li');
        li.textContent = '-'; 
        wordContainer.appendChild(li);
    });
}

renderWord(word);
