name: Notify Discord on Push

on:
  push:
    branches:
      - main  

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send push notification to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "📢 Yeni bir güncelleme yapıldı. Güncelleme mesajı: ${{ github.event.head_commit.message }}"
